core/src/client/client.rs, core/src/consensus/tendermint/engine.rs, state/src/impls/top_level.rs, state/src/item/metadata.rs, state/src/traits.rs
Copied from https://github.com/CodeChain-io/codechain/pull/1895
Some parts are revised to match the foundry's situation.
=> Read term_common_params from the state

sync/src/block/extension.rs, test/src/e2e.dynval/setup.ts, test/src/helper/spawn.ts
Ported from https://github.com/CodeChain-io/codechain/pull/1921
=> Refactoring patches from CodeChain/snapshot

core/src/block.rs, core/src/client/test_client.rs, core/src/consensus/mod.rs, core/src/consensus/simple_poa/mod.rs, core/src/consensus/solo/mod.rs, core/src/consensus/stake/action_data.rs, core/src/consensus/stake/mod.rs, core/src/consensus/tendermint/engine.rs, core/src/consensus/validator_set/dynamic_validator.rs, core/src/consensus/validator_set/mod.rs, core/src/consensus/validator_set/validator_list.rs, core/src/miner/miner.rs
Collected from https://github.com/CodeChain-io/codechain/pull/1900 and https://github.com/CodeChain-io/codechain/pull/1922
=> Update tendermint implementation to be compatible with snapshot sync

core/src/blockchain/blockchain.rs, core/src/blockchain/headerchain.rs, core/src/client/client.rs, core/src/client/importer.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/consensus/tendermint/worker.rs, foundry/config/mod.rs, foundry/foundry.yml, foundry/run_node.rs, sync/src/block/extension.rs, util/merkle/src/lib.rs, util/merkle/src/triedb.rs, util/merkle/src/triedbmut.rs
Depends: https://github.com/CodeChain-io/foundry/pull/19
Collected from https://github.com/CodeChain-io/codechain/pull/1855 and https://github.com/CodeChain-io/codechain/pull/1862
=> Import the snapshot header

core/src/client/client.rs, core/src/client/mod.rs, core/src/consensus/mod.rs, core/src/consensus/solo/mod.rs, core/src/lib.rs, foundry/rpc.rs, foundry/rpc_apis.rs, foundry/run_node.rs, rpc/src/v1/errors.rs, rpc/src/v1/impls/devel.rs, rpc/src/v1/impls/snapshot.rs, rpc/src/v1/traits/devel.rs, rpc/src/v1/traits/mod.rs, rpc/src/v1/traits/snapshot.rs, spec/JSON-RPC.md, test/src/e2e/snapshot.test.ts
Depends: https://github.com/CodeChain-io/foundry/pull/19
Collected from https://github.com/CodeChain-io/codechain/pull/1873 and https://github.com/CodeChain-io/codechain/pull/1869
=> Add RPCs for managing snapshots

core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/consensus/stake/action_data.rs, core/src/consensus/stake/mod.rs, core/src/consensus/tendermint/engine.rs, core/src/consensus/tendermint/worker.rs, core/src/consensus/validator_set/dynamic_validator.rs, core/src/consensus/validator_set/mod.rs, core/src/consensus/validator_set/validator_list.rs, foundry/run_node.rs, rpc/src/v1/impls/account.rs, rpc/src/v1/impls/chain.rs, rpc/src/v1/impls/engine.rs, rpc/src/v1/impls/mempool.rs
The patches in https://github.com/CodeChain-io/foundry/pull/27 were originally ported from the CodeChain's snapshot branch, which includes CurrentValidators patch in CodeChain-io/codechain#1922. I found out that there was something wrong about the previous implementation, and introduced PreviousValidator state value to solve this.
It's almost the same as the CurrentValidators, except that it is updated with the values from CurrentValidators.
The fee calculation function is changed a bit to utilize this state value. Please take a look at it carefully.
Some other patches not related to the fee calculation are included too. A detailed explanation is written in the commit messages.
=> Introduce PreviousValidators and fix tendermint bugs

core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/miner/mem_pool.rs, core/src/miner/miner.rs, rpc/src/v1/impls/mempool.rs, rpc/src/v1/traits/mempool.rs, test/src/e2e/mempool.test.ts
This new RPC takes no argument and deletes all pending transactions(both current and future), returning nothing.
(See https://github.com/CodeChain-io/codechain/pull/1941)
=> Add an RPC deleteAllPendingTransactions()

Cargo.lock, core/src/db.rs, core/src/lib.rs, core/src/peer_db.rs, foundry/run_node.rs, network/Cargo.toml, network/src/lib.rs, network/src/p2p/handler.rs, network/src/p2p/mod.rs, network/src/service.rs
To reduce the burden of bootstrap nodes, codecahin needs to save the received peer list
in the disk. In order to save the peer list of a node in the disk, a procedure is designed
a database to store nodes that are connected to the node.
=> Store the peer list on the DB of a node

core/src/consensus/stake/actions.rs, core/src/consensus/tendermint/message.rs, sync/src/block/message/mod.rs, sync/src/block/message/request.rs, sync/src/block/message/response.rs, types/src/errors/history_error.rs, types/src/errors/runtime_error.rs, types/src/errors/syntax_error.rs, types/src/transaction/shard.rs, vm/src/decoder.rs, vm/src/executor.rs, vm/src/instruction.rs, vm/src/lib.rs, vm/tests/executor.rs
I implemented the Encodable/Decodable in the enum type so that
the RLP code will receive enum type directly.
The compiler will warn programmers if there are missing enum values in a
match statement by using discriminated enums instead of constant type.
Using an enum type rather than constant type provides more safety
against type error.
=> Convert constants to discriminated enum

core/src/block.rs, core/src/client/test_client.rs, core/src/consensus/simple_poa/mod.rs, core/src/consensus/solo/mod.rs, core/src/miner/miner.rs, core/src/verification/verification.rs
Currently, the transactions root was the skewed merkle root of all
accumulated transactions from the genesis block. It changes the
definition of the transactions root to the skewed merkle root of
transactions in the block.
This change makes the node be able to verify a block's transactions
root without the parent header.
=> Calculate the transactions root with the transactions on the block

sync/src/block/downloader/body.rs, sync/src/block/extension.rs, types/src/header.rs
The definition of transactions_root has been changed.
It should be fixed by https://github.com/CodeChain-io/foundry/pull/101, but I missed.
=> Update the logic to check whether the block contains transactions

rpc/src/v1/impls/devel.rs, rpc/src/v1/traits/devel.rs, spec/JSON-RPC.md, sync/src/block/downloader/body.rs, sync/src/block/extension.rs
=> Add RPCs for checking peer best blocks & target blocks

core/src/db.rs, core/src/lib.rs, core/src/peer_db.rs, foundry/run_node.rs, network/src/p2p/handler.rs, network/src/service.rs
Hi @majecty and @MSNTCS,
I propose to improve PeerDb.
This PR includes 3 changes.
1. Change `Arc` to `Box`.
It's because there is only one holder of `PeerDb`.
2. Update disk once per 10 updates.
Since the current implementation update disk every time, it will query very much at the booting time.
I think we don't need it strongly consistent with the database since the purpose of PeerDb is backup addresses.
3. Store peer lists in one field.
Because we don't update db every time, we can use only one row to store the peer lists.
It also makes that the implementation of PeerDb corresponds between CodeChain and Foundry because it doesn't need to add a column.
=> Suggest to improve PeerDb

sync/src/block/downloader/body.rs, sync/src/block/extension.rs
Currently, Foundry doesn't mark the block as bad when the block is corrupted, but it doesn't re-request the body. This patch makes it re-send the request for the body.
~~It depends on https://github.com/CodeChain-io/foundry/pull/114.~~ #114 has been merged.
=> Re-send a body request when the body is corrupted

state/src/item/account.rs, state/src/item/dummy_shard_text.rs, state/src/item/metadata.rs, state/src/item/mod.rs, state/src/item/regular_account.rs, state/src/item/shard.rs, types/src/transaction/action.rs
This patch changes the state item prefixes and transaction tags to enumerations to make a compiler check duplications.
Actually, it's part of https://github.com/CodeChain-io/foundry/issues/38, but implementing and testing the issues takes more time than I expected. So I pushed it separately to avoid more conflicts.
=> Change constants to enumerations

core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/lib.rs, core/src/miner/mem_pool.rs, core/src/miner/mem_pool_types.rs, core/src/miner/miner.rs, core/src/miner/mod.rs, foundry/config/mod.rs, rpc/src/v1/impls/mempool.rs, rpc/src/v1/traits/mempool.rs, rpc/src/v1/types/mem_pool.rs, rpc/src/v1/types/mod.rs, spec/JSON-RPC.md
=> Add an RPC getting minimum fees confiugred by each machine

Cargo.lock, Cargo.toml, core/Cargo.toml, discovery/Cargo.toml, key/Cargo.toml, keystore/Cargo.toml, network/Cargo.toml, network/src/p2p/connection/mod.rs, network/src/p2p/handler.rs, network/src/p2p/message/extension.rs, network/src/routing_table.rs, network/src/session/session.rs, state/Cargo.toml, sync/Cargo.toml, types/Cargo.toml, vm/Cargo.toml
The version replaced the dependency of underlying crypto libraries.
To upgrade the version, it also upgrades codechain-db, merkle-trie and trie-standardmap which use codechain-crypto to resolve the dependency conflicts.
Because it upgrades merkle-trie, this change also makes the trie use caching.
=> Upgrade codechain-crypto to 0.2.0

core/src/ibc/connection_03/manager.rs, core/src/ibc/connection_03/mod.rs, core/src/ibc/connection_03/types.rs, core/src/ibc/transaction_handler/datagrams.rs, core/src/ibc/transaction_handler/mod.rs
This PR depends on ~https://github.com/CodeChain-io/foundry/pull/122~, #161 
Implement ICS connection issue: https://github.com/CodeChain-io/foundry/issues/156
=> Implement connOpenInit datagram in the ICS connection spec

core/src/client/client.rs, core/src/ibc/context.rs, core/src/ibc/transaction_handler/mod.rs, rpc/src/v1/impls/ibc.rs, state/src/ibc.rs, state/src/impls/top_level.rs
The connection spec's OpenTry datagram handler need to know the host's current height.
https://github.com/cosmos/ics/tree/master/spec/ics-003-connection-semantics
=> Add get_current_height function to the IBC Context

core/src/ibc/client_02/manager.rs, core/src/ibc/connection_03/manager.rs, core/src/ibc/transaction_handler/mod.rs, rpc/src/v1/impls/ibc.rs
~This PR depends on https://github.com/CodeChain-io/foundry/pull/178~
=> Add context field to `Manager`s in the IBC code

core/src/miner/miner.rs
I don't know the purpose of https://github.com/CodeChain-io/foundry/commit/f9f3c463daa66c0eb74672d2a356e1bc6e5bccca, so I'm not quite sure if this is a bug or not. 
But I think it doesn't make sense to print "Rejected" message and accept the transaction.
Could you have a look at it?
=> Return error when importing not allowed transactions

core/src/ibc/connection_03/manager.rs, core/src/ibc/context.rs, core/src/ibc/kv_store/mod.rs, core/src/ibc/transaction_handler/datagrams.rs, core/src/ibc/transaction_handler/mod.rs
~Depends on https://github.com/CodeChain-io/foundry/pull/180~
=> Implement ConnOpenConfirm datagram

core/src/consensus/light_client/mod.rs, core/src/consensus/light_client/verification.rs, core/src/ibc/mod.rs, core/src/ibc/querier/mod.rs, rpc/src/v1/impls/ibc.rs, rpc/src/v1/traits/ibc.rs, rpc/src/v1/types/ibc.rs, rpc/src/v1/types/mod.rs
=> Implement RPCs for client_02

core/src/ibc/connection_03/manager.rs, core/src/ibc/connection_03/mod.rs, core/src/ibc/connection_03/types.rs, core/src/ibc/querier/mod.rs, rpc/src/v1/impls/ibc.rs, rpc/src/v1/traits/ibc.rs, rpc/src/v1/types/ibc.rs, rpc/src/v1/types/mod.rs
~I left the proof part. I'll update this PR after Junha finish https://github.com/CodeChain-io/foundry/pull/196~
Now, I'm ready for review.
=> Impement queryConnection and queryClientConnections

core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/miner/mem_pool.rs, core/src/miner/miner.rs, core/src/miner/mod.rs, rpc/src/v1/impls/mempool.rs, rpc/src/v1/traits/mempool.rs, spec/JSON-RPC.md, test/package.json, test/src/e2e/mempool.test.ts, test/yarn.lock
The change is supposed to include the future queue in pending transactions as well. Previously, we only had the current queue. Now, `mempool_getPendingTransactions` can return either the `current queue` or both the `current` and `future queues`. In order to have `future queue`, the boolean `future_included` parameter is considered. It fixes #150
=> Modify getPendingTransactions and countPendingTransaction to include future transactions

test/src/e2e.long/tendermint.test.ts, test/src/helper/error.ts
Previously, when there was codechain dependency tenderminet could handle Engine
error. Foundry rpc can not handle Engine error. In this patch, the Engin error
is handled.
=> Adapt tendermint test to handle Engine error

core/src/consensus/tendermint/engine.rs
The previous patch changes it to read the term seconds of the parent
common params. It changed the behavior and made the "Change term
seconds" test fail.
=> Read term seconds from the common params of parent term

core/src/ibc/channel_04/manager.rs, core/src/ibc/context.rs, core/src/ibc/transaction_handler/datagrams.rs, core/src/ibc/transaction_handler/mod.rs, ibc.ts/src/common/chain.ts, ibc.ts/src/common/datagram/chanOpenAck.ts, ibc.ts/src/common/datagram/chanOpenConfirm.ts, ibc.ts/src/common/datagram/chanOpenInit.ts, ibc.ts/src/common/datagram/chanOpenTry.ts, ibc.ts/src/common/datagram/index.ts, ibc.ts/src/common/types.ts, ibc.ts/src/relayer/index.ts, ibc.ts/src/scenario/index.ts
I wrote code that builds a channel between two chains.
~I found that there is an error while verifying the connection hops. I'll fix it soon after reading the channel spec again.~
I fixed all the errors.
=> Build a channel

core/src/ibc/channel_04/log.rs, core/src/ibc/channel_04/manager.rs, core/src/ibc/channel_04/types.rs, core/src/ibc/transaction_handler/datagrams.rs, ibc.ts/chainA/chainA.schem.json, ibc.ts/chainB/chainB.schem.json, ibc.ts/src/common/chain.ts, ibc.ts/src/common/datagram/acknowledgePacket.ts, ibc.ts/src/common/datagram/index.ts, ibc.ts/src/common/datagram/recvPacket.ts, ibc.ts/src/common/datagram/sendPacket.ts, ibc.ts/src/relayer/index.ts, ibc.ts/src/scenario/index.ts, rpc/src/v1/impls/ibc.rs, rpc/src/v1/traits/ibc.rs, rpc/src/v1/types/ibc.rs
I wrote code to send and relay packets.
~While I testing it, I met an unexpected error: "Illformed Sequence stored in the DB: RlpExpectedToBeData".
I'll fix it soon.~
=> Send and relay packet

core/src/block.rs, core/src/client/client.rs, core/src/client/importer.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/consensus/solo/mod.rs, core/src/miner/miner.rs
Resolves #261 
There is no reason to distinguish ClosedBlock and LockedBlock since
ClosedBlocks are never reopened.
reopen methods should be removed as well.
=> Merge ClosedBlock and LockedBlock into one

test/src/e2e.dynval/2/snapshot.test.ts
This test becomes fragile. Let's skip it until we stabilize the snapshot feature.
=> Skip one of the snapshot test

test/src/e2e.long/staking.test.ts
Other getBalance callers are converting the return value to number using "+". Only this line does not have it.
=> Convert hexadecimal string returned from getBalance to number

core/src/blockchain/blockchain.rs, core/src/blockchain/mod.rs, core/src/blockchain/route.rs, core/src/blockchain/update_result.rs, core/src/client/importer.rs
Resolves #230 
We don't use the `omitted` field anymore.
I'm not sure if I should remove `ImportRoute` struct at all, or leave it. 
Please give a comment.
=> Remove omitted field from ImportRoute

core/src/block.rs, core/src/blockchain/blockchain.rs, core/src/blockchain/body_db.rs, core/src/blockchain/extras.rs, core/src/blockchain/invoice_db.rs, core/src/blockchain/mod.rs, core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/invoice.rs, rpc/src/v1/impls/chain.rs, rpc/src/v1/impls/mempool.rs, rpc/src/v1/traits/chain.rs, rpc/src/v1/traits/mempool.rs, spec/JSON-RPC.md
This PR will remove tracker from transaction invoice and body db.
I didn't remove tracker entirely, because currently `ShardState` makes use of it.
Since shard will be removed, eventually tracker will be removed as well.
Remaining work should be done after `ShardState` is removed.
=> Remove tracker from invoice and body db

core/src/block.rs, core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/codechain_machine.rs, core/src/consensus/mod.rs, core/src/consensus/tendermint/worker.rs, core/src/lib.rs, core/src/miner/backup.rs, core/src/miner/mem_pool.rs, core/src/miner/mem_pool_benches.rs, core/src/miner/mem_pool_types.rs, core/src/miner/miner.rs, core/src/miner/mod.rs, core/src/tests/helpers.rs, core/src/transaction.rs, core/src/verification/verification.rs, foundry/auto_self_nominate.rs, rpc/src/v1/impls/chain.rs, rpc/src/v1/impls/devel.rs, rpc/src/v1/impls/mempool.rs, rpc/src/v1/types/transaction.rs, sync/src/block/extension.rs, sync/src/transaction/extension.rs
Summary: We modified logic related to the transaction type for checking whether a transaction is verified or not. From now on, there are two transaction types, `UnverifiedTransaction` and `VerifiedTransaction`, and the `UnverifiedTransaction` can be converted to `VerifiedTransaction` using the method `try_into()`. During this conversion, the signature is verified through the method `verify_transaction()`.
---
We were using two transaction types, `UnverifiedTransaction` and `SignedTransaction`. The `SignedTransaction` was constructed from an `UnverifiedTransaction` when the signature recovery returned a public key without errors. These structs were as follows:
```rust
pub struct UnverifiedTransaction {
/// Plain Transaction.
unsigned: Transaction,
/// Signature.
sig: Signature,
/// …
```
=> Modify logic related to the Tx type for checking whether a Tx is verified or not

Cargo.lock, Cargo.toml, foundry/config/mod.rs, foundry/config/presets/config.dev.toml, foundry/config/presets/config.prod.toml, foundry/foundry.yml, foundry/run_node.rs, informer/Cargo.toml, informer/src/handler/connection.rs, informer/src/handler/mod.rs, informer/src/handler/rpc_ws_handler.rs, informer/src/informer_service/informer_notify.rs, informer/src/informer_service/informer_service_handler.rs, informer/src/informer_service/mod.rs, informer/src/lib.rs, informer/src/rpc_server.rs, network/Cargo.toml, network/src/p2p/handler.rs, network/src/service.rs, test/src/config/mem-pool-min-fee1.toml, test/src/config/mem-pool-min-fee2.toml, test/src/helper/spawn.ts, test/tendermint.dynval/snapshot-config.yml, util/logger/src/macros.rs
Informer API is supposed to send events as soon as they are triggered to all subscribed clients. In this PR, Hot events, those are not retrieved from the history of the event, are covered.
=> Hot events for Informer API 

core/src/client/chain_notify.rs, core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/service.rs, sync/src/transaction/extension.rs
=> Remove ChainNotify::transactions_received()

test/src/e2e/changeParams.test.ts
Some e2e tests are emitting `UnhandledPromiseRejectionWarning`. When we run the tests, we can see the following warning:
```
ChangeParams
✓ change (38ms)
(node:13789) UnhandledPromiseRejectionWarning: Error: CodeChain(3) process state is invalid: {
"state": "stopping"
}
at CodeChain.get testFramework [as testFramework] (/home/spkim2/foundry/test/src/helper/spawn.ts:100:19)
at CodeChain.createPayTx (/home/spkim2/foundry/test/src/helper/spawn.ts:547:21)
at CodeChain.sendPayTx (/home/spkim2/foundry/test/src/helper/spawn.ts:572:25)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:13789) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch …
```
=> Resolve `UnhandledRejectionWarning` in e2e tests

Cargo.lock, coordinator/src/context.rs, coordinator/src/validator.rs, state/Cargo.toml, state/src/cache/global_cache.rs, state/src/cache/lru_cache.rs, state/src/cache/mod.rs, state/src/cache/module_cache.rs, state/src/cache/top_cache.rs, state/src/cache/write_back.rs, state/src/db/state_db.rs, state/src/impls/mod.rs, state/src/impls/module_level.rs, state/src/impls/test_helper.rs, state/src/impls/top_level.rs, state/src/item/address.rs, state/src/item/metadata.rs, state/src/item/mod.rs, state/src/item/module.rs, state/src/item/module_datum.rs, state/src/lib.rs, state/src/traits.rs, types/src/errors/runtime_error.rs, types/src/lib.rs
Now, the `DbContext` is implemented for the minimal unit `TopLevelState`. In the future, the state manager, who owns or manages the latest top level state, can implement `DbContext` using the methods already implemented in `TopLevelState`
=> Implement module db for coordinator Context

core/src/client/client.rs, core/src/client/test_client.rs, core/src/codechain_machine.rs, core/src/miner/miner.rs, core/src/miner/mod.rs, core/src/scheme/scheme.rs
Since CommonParams is saved to and restored from the state, the machine does not need to hold it.
FIXME in ready_transactions is resolved accordingly.
Now CodeChainMachine has no field, so I'm not sure if we further refactor this or not.
=> Remove genesis_common_params from machine

network/src/p2p/handler.rs, network/src/stream.rs
This PR fixes https://github.com/CodeChain-io/foundry/issues/308
There are a few things to do more.
1. Should we catch the error in the places?
2. What should we do when we met other IO errors? Should we disconnect the socket?
3. What happens if we write bytes to a disconnected socket? (This PR only checks the `read` call).
=> Disconnect a socket If Foundry meets EOF while reading the socket

core/src/consensus/mod.rs
It is not used.
Furthermore, the concept of block fee will be removed from the host side at all, eventually.
=> Remove block_fee method

core/src/client/client.rs, core/src/scheme/scheme.rs
We gain nothing from initializing extra data of genesis header with
hash of common params, because the check will be done by the same node,
and it will always succeed.
We can just use extra_data written in scheme file.
=> Remove unnecessary initialization of genesis header extra data

core/src/block.rs
We removed static validator set before.
=> Remove deprecated comment about static validator

coordinator/src/lib.rs
The function doesn't need a new type parameter.
=> Rename Builder::create to Builder::new

test/src/e2e.dynval/2/dv.shutdown.test.ts, test/src/e2e.long/staking.test.ts
This PR fixes two tests.
The first test assumes that there is no block between transactions. This assumption is usually correct, but you cannot guarantee it because sometimes the engine generates a block without transactions because of the timeout.
The commit fixes the test to query the block number before sending transactions.
The second test depends on delicate timing. The test fails when the node of betas creates a block between to stop nodes and term changing. The commit changes nodes to restart nodes except the betas and to start betas after the term has been changed.
=> Fix the flaky staking e2e tests

core/src/block.rs, core/src/client/test_client.rs, core/src/miner/miner.rs, foundry/run_node.rs
This refactoring is done to implement https://github.com/CodeChain-io/foundry/pull/324. But, because the PR takes more time than expected, I extracted the refactoring commits.
=> Simplify miner, client and block.

Cargo.lock, module/Cargo.toml, module/src/link.rs, module/src/sandbox.rs
This is what @junha1 will implement.
* Removed dependency on crossbeam in favor of simple Receiver trait. Messages are anyway likely queued elsewhere to send to a module, so we don't need to buffer them separately with crossbeam channels.
* Service objects are created at module creation time, and handles of some of them are exchanged at link creation time.
=> Revise module protocols

.travis.yml
I'm not quite familiar with Travis CI configuration.
Please tell me if this is insufficient.
=> Temporarily disable Travis CI in mold

coordinator/src/context.rs, core/src/client/client.rs
~~It can only be merged after @Byeongjee 's branch `byeongjee/implement.validator.interface.call` is landed.
This pr includes only one commit `80bdd5`~~
=> Implement MemPoolAccess as a part of the context

test/src/e2e.long/bootstrap.test.ts
We should call checkfulfilled to ensure the promise is called.
=> Add missed promiseExpect.checkfulfilled

coordinator/src/lib.rs, coordinator/src/test_coordinator.rs, coordinator/src/traits.rs, coordinator/src/types.rs, core/src/block.rs, core/src/consensus/mod.rs, core/src/consensus/solo/mod.rs, core/src/consensus/tendermint/engine.rs, core/src/error.rs, core/src/miner/miner.rs
Now BlockOutcome contains a reason for a block rejection and
update_validator_set and updated_consensus_params are optional.
Also, execute_transactions returns execution outcome.
=> Modify BlockExecutor trait methods' return types

core/src/block.rs, sync/src/block/message/mod.rs, sync/src/block/message/response.rs, sync/src/transaction/message.rs, test/src/helper/mock/cHeader.ts, test/src/helper/mock/test/header.test.ts, types/src/header.rs
=> Fix header RLP encoding in mock code

coordinator/src/lib.rs, coordinator/src/test_coordinator.rs, coordinator/src/traits.rs, coordinator/src/types.rs, core/src/block.rs, core/src/client/client.rs, core/src/client/mod.rs, core/src/client/test_client.rs, core/src/miner/mem_pool.rs, core/src/miner/mem_pool_types.rs, core/src/miner/miner.rs, core/src/miner/mod.rs, rpc/src/v1/impls/mempool.rs, sync/src/transaction/extension.rs
Resolves #370 
`mem_pool.top_transactions` should be removed.
We may need a separate interface dedicated to handle `ready_transactions` method.
=> Change fetch_transactions_for_block interface

Cargo.lock, basesandbox/Cargo.toml, basesandbox/src/execution/executor.rs, basesandbox/src/ipc.rs, basesandbox/src/ipc/intra.rs, basesandbox/src/ipc/multiplex.rs, basic_module/account/src/lib.rs
We use `parking_lot` instead of the standard Mutex.
It's more efficient and easy to use.
=> Use parking_lot instead of the standard sync primitives

Cargo.lock, Cargo.toml, basic_module/account/src/core.rs, basic_module/account/src/impls.rs, basic_module/account/src/lib.rs
When the prototype of the Account module was merged, there was a mistake that did not designate `impls.rs` as the build target. I modified it as a build target and some code, so that we could compile it.
The commit in this PR includes
- Modify impls.rs to complie it
- Remove the trait SignatureManager
=> Modify impls.rs in Account module which was not compiled

Cargo.lock, Cargo.toml, basic_module/staking/Cargo.toml, basic_module/staking/src/check.rs, basic_module/staking/src/core.rs, basic_module/staking/src/error.rs, basic_module/staking/src/execute.rs, basic_module/staking/src/impls.rs, basic_module/staking/src/imported.rs, basic_module/staking/src/lib.rs, basic_module/staking/src/runtime_error.rs, basic_module/staking/src/state.rs, basic_module/staking/src/syntax_error.rs, basic_module/staking/src/transactions.rs, basic_module/staking/src/types.rs, coordinator/src/types.rs
I tried to simulate staking logic previously is operating inside the host.
If it is merged into mold, the following tasks should be carried out.
1. Remove staking logic from the host.
2. Modify `TopLevelState` to store only CompactValidatorSet which contains only validators' public key and abstract voting powers. 
3. Remove parameters only used by `Staking`.
Followings are not implemented yet:
1. Executing `ReportDoubleVote` and banning malicious validators.
2. Creating transactions from higher level input (e.g. graphQL mutation request)
=> Implement Staking module

core/src/block.rs, core/src/blockchain/body_db.rs, core/src/blockchain/extras.rs, core/src/client/test_client.rs, core/src/consensus/tendermint/worker.rs, core/src/consensus/validator_set/dynamic_validator.rs, core/src/miner/miner.rs, core/src/transaction.rs, core/src/types/transaction_id.rs, core/src/views/block.rs, core/src/views/body.rs, rpc/src/v1/types/block.rs, rpc/src/v1/types/transaction.rs, state/src/impls/top_level.rs, state/src/item/stake.rs, state/src/stake/actions.rs, state/src/stake/mod.rs, test/src/e2e.long/tendermint.test.ts, test/src/stakeholder/actionData.ts, types/src/lib.rs, types/src/transaction/action.rs, types/src/transaction/validator.rs
By sorting the validator set using public keys, we can make validator set hash consistent. We can use this property to omit the validator set hash in Header Sync.
If two validators have the same delegation and deposit, the one who became the candidate first will be validator first. We didn't change the rule in this commit. Previously we kept the order of Candidates and Validators to remember who became the candidate first. Now we are saving nomination_starts_at variable to remember it.
=> Sort validator set in public key order

core/src/miner/miner.rs, test/package.json, test/src/e2e.dynval/2/snapshot.test.ts, test/src/e2e.dynval/setup.ts, test/src/e2e/snapshot.test.ts, test/src/e2e/staking.test.ts, test/src/helper/mock/example/send-tx.ts, test/src/helper/spawn.ts, test/src/sdk/index.ts, test/yarn.lock
@sgkim126 Could you check "Make Foundry makes blocks slowly if RUN_ON_TEST is set" commit carefully. I'm not sure using an environment variable and the `sleep` method is good or not.
=> Fix few things in test code

basic_module/account/src/impls.rs, basic_module/account/src/import.rs, basic_module/account/src/lib.rs, basic_module/staking/src/execute.rs, basic_module/staking/src/impls.rs, basic_module/staking/src/imported.rs, basic_module/staking/src/lib.rs, basic_module/staking/src/types.rs
This pr removes two interfaces: `FeeManager`; `SignatureManager`.
For the former, we do not have to consider the unimplemented module `Distribution`. For the latter, each module can verify signature with help of the `foundry/key` crate.
=> Clean unnecessary interfaces

basic_module/account/src/core.rs, basic_module/account/src/impls.rs, basic_module/account/src/internal.rs
The variables named 'account' had public key as its value. We judged
that the name was inappropriate to have the value, so I renamed the name
`address` to `account_id`.
=> Rename 'address' to 'account_id'

Cargo.lock, Cargo.toml, coordinator/Cargo.toml, coordinator/src/context.rs, coordinator/src/context/chain_history_access.rs, coordinator/src/context/mem_pool_access.rs, coordinator/src/context/storage_access.rs, coordinator/src/context/sub_storage_access.rs, coordinator/src/header.rs, coordinator/src/lib.rs, coordinator/src/test_coordinator.rs, coordinator/src/traits.rs, coordinator/src/transaction.rs, coordinator/src/types.rs, coordinator/src/types/event.rs, types/src/consensus_params.rs, types/src/lib.rs, types/src/validator_set.rs
This PR reorders, re-structs, and squshes the commits in the mold branch.
The commits are
* 632ede45d (mold) Implement StateHistoryAccess for Client
* a383e0322 Add a method to the host side to transfer Header
* 9634e7a43 Use boxed iterator instead of slice of references in filter_transactions
* 02ad51fd9 Change fetch_transactions_for_block into prepare_transactions_with_result
* b263c6aad Deliver transaction hashes when injection
* 9b41137e1 Change the return type of open_block to Result
* d77d21c8a Change return the type of execute_transactions to Result
* 1cff4c388 Change the return type of close_block to Result
* 7db3a183b Make updated entries in BlockOutcome optional
* 2336b11bc Remove storage_id from methods in SubStorageAccess
* 21189f790 Implement MemPoolAccess trait
* b20ecc0f5 …
=> Add Coordinator to the master branch

core/src/miner/miner.rs
I copied changes from CodeChain's PR https://github.com/CodeChain-io/codechain/pull/1968
=> Reduce lock region

Cargo.lock, Cargo.toml, basic_module/account/Cargo.toml, basic_module/account/src/core.rs, basic_module/account/src/error.rs, basic_module/account/src/impls.rs, basic_module/account/src/internal.rs, basic_module/account/src/lib.rs, basic_module/account/src/types.rs, coordinator/src/lib.rs
This PR reorganized the commits below.
* 586dc887 Do not consider the distribution module
* 72ecd89f Modify the implementation of Account module
* b07edc1e Use parking_lot instead of the standard sync primitives
* 416750d8 Implement the trait SignatureManager
* c6db9f0e Implement the trait AccountView
* 3f21b974 Implement the trait AccountManager
* d12b403c Impelment the trait TransactionExecutor
* 46948065 Impelment the trait CheckTxHandler
* f4a62412 Implement internal functions
* fdd8322e Declare methods imported from external
* 8e5c16e2 Declare error handling and types for the module
* 81ebff60 Initialize for implementing the module Account
This commit depends on https://github.com/CodeChain-io/foundry/pull/396. I'll remove `do-not-merge` after the PR merged.
=> Port the account module

core/src/client/client.rs, core/src/client/importer.rs
Currently, the client access the miner through the importer. It's better to give a method to access the miner directly.
It closes #44. The issue suggests moving the miner to the client. However, because the importer holds the arc of the miner, we can make both of the importer and the client hold the miner. I think it's better than moving because the importer also needs the miner.
=> Make the client hold the miner directly

core/src/client/test_client.rs, core/src/miner/mem_pool.rs, core/src/miner/miner.rs, core/src/miner/mod.rs
We found that mempool mis-calculates sequence in the TPS test. After
fixing the mempool to read consistent state, mempool calculates
sequence well.
Copied from https://github.com/CodeChain-io/codechain/pull/1976
=> Fetch consistent state in mempool functions

informer/src/handler/subscription.rs
In this commit, we change the name of the block generation event on informer API.
=> Change block generation event parameter name

basic_module/staking/src/execute.rs, coordinator/src/context/sub_storage_access.rs
I found the SubStorageAccess takes the immutable references. But, it's safer to take the mutable reference when it changes the internal value because it makes only one thread be able to mutate the values.
=> Change the mutability of SubStorageAccess

core/src/client/client.rs, core/src/client/test_client.rs, core/src/miner/mem_pool.rs, core/src/miner/mem_pool_types.rs, core/src/miner/miner.rs, core/src/miner/mod.rs
The only information in the structs is the number of pending transactions,
so we don't need such abstraction anymore.
=> Remove unnecessary MinerStatus and MemPoolStatus

voting/src/general_meeting.rs, voting/src/voting.rs
If a module supposes to write in its own state, it should consider to export `stateful` as a service. In this PR, we add missing `stateful` export service for both `general_meeting` and `voting` modules.
=> Add missing stateful export service for both general_meeting and voting modules 

state/src/impls/module_level.rs, state/src/impls/top_level.rs
WriteBack cache panic when it is cloned while it has a check point. This
commit makes ReadOnlyModuleLevelState borrow the cahce.
=> Make module level do not clone the cache to read value

voting/src/general_meeting.rs, voting/src/voting.rs, voting/tests/common/mock_coordinator.rs, voting/tests/common/scenarios.rs, voting/tests/integration_test.rs
Some parts of the previous implementation that was needed for tests seemed to be incomplete. In this PR, first, we complete the previous implementation, then implement a test for the CreateVotePaper transaction.
=> Implement tests for CreateVotePaper transaction

foundry/foundry.yml
Some foundry commands have not been used in the code and they do not have any functionalities. In this PR, we remove them.
=> Remove Obsolete commands 

coordinator/src/test_coordinator.rs
unimplemented!()s in the previous impl caused panick during some tests.
Made the trait methods return reasonable default values.
=> Fill up GraphQlHandlerProvider impl for TestCoordinator

core/src/client/client.rs
There was no code that save Genesis state in DB.
It may be saved when Foundry saves block number 1, but it is not normal.
Corresponding CodeChain code writes the data to DB: https://github.com/CodeChain-io/codechain/blob/b82ca0ce594f67ef6179d2453c2b996f8648c584/core/src/client/client.rs#L104
=> Save the genesis state in DB

core/src/block.rs
It was called in the enact function which is used to verify a
block. However it was not called when generating a block.
update_next_block_state is called in the close function. For the
consistency, this commit make the `open` function call the
update_current_validator_set.
=> Call update_current_validator_set in the block.open

coordinator/src/context/storage_access.rs, coordinator/src/lib.rs, core/src/miner/mem_pool.rs, state/src/impls/top_level.rs
Previously coordinator cached max_body_size when initializing the
genesis block. It was not a correct implementation. When we modify the
max_body_size in the state DB, the cached content and the DB content
will not be the same.
This commit makes the coordinator read max_body_size from the DB. Now,
we only have a source of truth.
=> Read max_body_size from state

coordinator/src/app_desc/genesis.rs, core/src/genesis.rs
We only need a field to change genesis header's hash.
=> Remove unnecessary genesis configurations

core/src/miner/miner.rs, demo/config0.toml, demo/config1.toml, demo/config2.toml, demo/config3.toml, foundry/config/mod.rs, foundry/config/presets/config.dev.toml, foundry/config/presets/config.prod.toml, foundry/foundry.yml, foundry/run_node.rs, integration-test/config.tendermint-solo.toml
* quiet: It was not used.
* author: Originally used in PoW consensus. Foundry does not use PoW.
* self_nomination_metadata, self_target_deposit,
self_nomination_enable, self_nomination_interval: They are related to
CodeChain dynamic validator. Foundry does not enforce a specific
validator rule.
* mem_pool_fee_bump_shift: It was used to manage mempool. In Foundry,
modules will manage the mem pool.
=> Remove unused configs

Cargo.toml, foundry/lib.rs, foundry/main.rs
Currently, we can use only timestamp modules.
By splitting main and lib we can use other modules easily.
=> Split foundry lib and main

key/src/lib.rs, key/src/random.rs
"Seal" can be confusing since it is used for signatures for block.
=> Rename seal to encryption

key/src/encryption.rs
This does not check the code we wrote. It will help developer to understand the characteristic of `encrypt` function.
=> Add a test that check whether the encryption result is deterministic or not

network/src/p2p/handler.rs, sync/src/block/extension.rs
I copied the commit from https://github.com/CodeChain-io/foundry/pull/499
This PR is a hotfix for https://github.com/CodeChain-io/foundry/issues/274
I tried to import two commits in the #499 PR. However "Fix the mismatch number of peer connections" made Foundry not to connect each other.
=> Hotfix the duplicate connection bug

core/src/consensus/validator_set/dynamic_validator.rs
This commit assumes that the validator set is not changed.
=> Make Foundry use all validators as proposer
