core/src/lib.rs
spec/Block-Synchronization-Extension.md
sync/src/block/downloader/header.rs
sync/src/block/extension.rs
sync/src/block/message/mod.rs
sync/src/block/message/request.rs
sync/src/block/message/response.rs
test/src/helper/mock/blockSyncMessage.ts

Collected from https://github.com/CodeChain-io/codechain/pull/1843 and https://github.com/CodeChain-io/codechain/pull/1864

Update messages of the block sync extension

---

spec/JSON-RPC.md

see https://github.com/CodeChain-io/codechain/pull/1952

Update JSON-RPC.md with the new RPC 'mempool_deleteAllPendingTransactions()'

---

core/src/verification/queue/mod.rs

It depends on https://github.com/CodeChain-io/foundry/pull/101.

Do not prohibit headers whose body is malformed

---

core/src/block.rs
core/src/blockchain/blockchain.rs
core/src/blockchain/invoice_db.rs
core/src/consensus/tendermint/worker.rs
core/src/miner/mem_pool.rs
core/src/miner/miner.rs
core/src/miner/mod.rs

It closes #32 
I couldn't cherry-pick  https://github.com/CodeChain-io/codechain/pull/1933/commits/25f1a6bb9db55a98804af43c6390b2f608c86389 failed, probably due to changes introduced by https://github.com/CodeChain-io/foundry/commit/c7db6519d9e9a06262d4cb88d7eae135972f08d6. 
I'm not sure whether we should introduce https://github.com/CodeChain-io/codechain/pull/1933/commits/25f1a6bb9db55a98804af43c6390b2f608c86389 to our current foundry code or not.

Apply the PR that cleans up the core module

---

core/src/miner/mem_pool.rs
core/src/miner/mem_pool_benches.rs
core/src/miner/mem_pool_types.rs
core/src/miner/miner.rs
test/src/e2e/mempool.test.ts

 Remove TxTimlock from the mempool

---

core/src/ibc/transaction_handler/mod.rs

The context is created in all datagram handlers.
~This PR depends on https://github.com/CodeChain-io/foundry/pull/166.~

Extract a context variable in the IBC transaction handler

---

core/src/consensus/stake/action_data.rs
types/src/lib.rs
types/src/validator_set.rs

As @majecty suggested https://github.com/CodeChain-io/foundry/pull/172#discussion_r381087816

Refactor CompactValidatorSet to impl Deref

---

test/yarn.lock

I found the lock file is not updated when I ran the e2e tests.

Update yarn.lock file

---

core/src/ibc/channel_04/log.rs
core/src/ibc/channel_04/manager.rs
core/src/ibc/channel_04/mod.rs
core/src/ibc/channel_04/types.rs
core/src/ibc/client_02/manager.rs

There are still missing required functions, since we don't need it in PoC

Implement ICS 04

---

core/src/ibc/transaction_handler/datagrams.rs
core/src/ibc/transaction_handler/mod.rs

Depends on https://github.com/CodeChain-io/foundry/pull/218

Implement Datagram & transaction handler for ICS04

---

core/src/consensus/light_client/mod.rs
core/src/consensus/light_client/verification.rs
core/src/consensus/stake/action_data.rs
core/src/ibc/client_02/client.rs
core/src/ibc/client_02/types.rs
rpc/src/v1/impls/ibc.rs

Previous algorithm has a critical problem.

Fix light client

---

test/package.json
test/src/sdk/key/KeyStore.ts
test/src/sdk/key/LocalKeyStore.ts
test/src/sdk/key/MemoryKeyStore.ts
test/src/sdk/key/RemoteKeyStore.ts
test/src/sdk/key/__test__/LocalKeyStore.spec.ts
test/src/sdk/key/__test__/MemoryKeyStore.spec.ts
test/src/sdk/key/index.ts
test/yarn.lock

It can be merged only after the #154

Fit test framework types into foundry-keystore

---

core/src/ibc/channel_04/manager.rs
core/src/ibc/client_02/manager.rs

Channel should not know the format of the ClientState.

Do not export ClientState to channel

---

core/src/client/client.rs
core/src/client/importer.rs

This should have been done in https://github.com/CodeChain-io/foundry/pull/256

Rename ChainUpdateResult variables

---

state/src/cache/global_cache.rs
state/src/cache/top_cache.rs
state/src/impls/module_level.rs
state/src/impls/test_helper.rs
state/src/impls/top_level.rs

This pr enhances module level db test cases and fixes two bugs revealed by the test implementations.

Fix top level state bugs and enhance test cases

---

state/src/impls/test_helper.rs
state/src/impls/top_level.rs

These commits are cherry-picked from the mold branch.

Refactor TestHelper for states

---

core/src/miner/miner.rs
foundry/config/mod.rs
foundry/config/presets/config.dev.toml
foundry/config/presets/config.prod.toml
test/src/e2e/shard.test.ts
test/src/sdk/core/transaction/CreateShard.ts

This commit is extracted from d8ca4dd67a57958914234acb1f126c4ea52c7c66.

Remove the allow-create-shard flag

---

state/src/cache/global_cache.rs
state/src/cache/top_cache.rs
state/src/impls/top_level.rs

This commit is cherry-picked from the mold branch.

Fix bugs in the top level state and global cache

---

coordinator/src/validator.rs

Do you have a reason to make them optional?

Change the fields of ConsensusParams to non optional

---

Cargo.lock
Cargo.toml
basesandbox/Cargo.toml
basesandbox/src/execution.rs
basesandbox/src/execution/executee.rs
basesandbox/src/execution/executor.rs
basesandbox/src/ipc.rs
basesandbox/src/ipc/domain_socket.rs
basesandbox/src/ipc/intra.rs
basesandbox/src/lib.rs
basesandbox/tests/intergration_test.rs
basesandbox/tests/simple.rs

This is part of https://github.com/CodeChain-io/foundry/pull/289 and created to merge it partially.

Implement IPC

---

module/schema/app-desc.yaml
module/schema/idl.yaml

JSON scheams written in YAML + [YTT](https://github.com/k14s/ytt/).
No build script to generate JSON from them yet, but I will add one soon.

Add schemas for app-desc and IDL

---

basesandbox/src/ipc.rs
basesandbox/tests/intergration_test.rs

Fix IPC random name generator

---

coordinator/src/context.rs
coordinator/src/lib.rs
coordinator/src/test_coordinator.rs
coordinator/src/traits.rs
state/src/impls/top_level.rs

Remove explicit argument 'storage_id' from SubStorageAccess trait

---

test/src/e2e.long/onChainBlockValid.test.ts
test/src/e2e.long/onChainHeaderValid.test.ts
test/src/helper/chai-similar.ts
test/src/helper/mock/index.ts

I will enhance this test to check signature verification of precommits later.

Add header sync test

---

core/src/miner/mem_pool_types.rs

It's hard to understand the meaning without the comment.

Restore a mistakenly removed comment

---

coordinator/src/context.rs
core/src/client/client.rs

Deliver transaction hashes when injection

---

Cargo.lock
basesandbox/Cargo.toml
basesandbox/src/execution/executee.rs
basesandbox/src/execution/executor.rs
basesandbox/src/ipc.rs
basesandbox/src/ipc/domain_socket.rs
basesandbox/src/ipc/intra.rs
basesandbox/src/ipc/multiplex.rs
basesandbox/src/ipc/servo_channel.rs
basesandbox/tests/intergration_test.rs
basesandbox/tests/simple/simple.rs

This PR contains multiple commits. 
Most of them are for fixing bugs, and others are preparations for FML PR.
This change is due to MacOS slightly different behavior of using domain socket. 
I must use `connect()` to use `shutdown()` in MacOS. There are some minor differences but this is the main background of this PR.

Upgrade IPC

---

types/src/consensus_params.rs

@sgkim126 Could you merge it to mold and apply this change to #396?

Remove max_gas_total from ConsensusParams

---

basic_module/staking/src/lib.rs
basic_module/staking/src/state.rs
basic_module/staking/src/types.rs

The logic was copied from `stake/action.rs`

Add a function initializing the staking module

---

coordinator/src/types.rs
core/src/block.rs
core/src/consensus/mod.rs
core/src/consensus/tendermint/mod.rs
core/src/miner/miner.rs

Modules require information about the committed validators of last
block.

Add last_committed_validators field to the Header

---

core/src/miner/miner.rs

Remove the transaction listener on the miner

---

core/src/miner/miner.rs
foundry/config/mod.rs
foundry/config/presets/config.dev.toml
foundry/config/presets/config.prod.toml

Remove no-reseal-timer option

---

Cargo.lock
coordinator/src/context.rs
coordinator/src/header.rs
core/Cargo.toml
core/src/client/client.rs
core/src/encoded.rs
state/Cargo.toml
state/src/impls/top_level.rs

~It depends on https://github.com/CodeChain-io/foundry/pull/405~

Implement coordinator contexts for the client

---

Cargo.lock
Cargo.toml
timestamp/Cargo.toml
timestamp/src/account.rs
timestamp/src/common.rs
timestamp/src/lib.rs
timestamp/src/staking.rs
timestamp/src/stamp.rs
timestamp/src/tests.rs
timestamp/src/token.rs

All commits are same as in `timestamp` branch except the last one

Bring timestamp branch

---

Cargo.lock
Cargo.toml
build.rs

This commit is picked from the mold branch.

Upgrade vergen 3

---

core/src/block.rs
core/src/blockchain/blockchain.rs
core/src/blockchain/body_db.rs
core/src/client/client.rs
core/src/client/importer.rs
core/src/client/test_client.rs
core/src/consensus/mod.rs
core/src/encoded.rs
core/src/lib.rs
core/src/scheme/scheme.rs
core/src/tests/helpers.rs
core/src/verification/verification.rs
core/src/views/block.rs
core/src/views/body.rs
sync/src/block/downloader/body.rs
sync/src/block/extension.rs
sync/src/block/message/response.rs
test/src/e2e.long/onChainBlockValid.test.ts
test/src/sdk/core/Block.ts

This is a composition of 2140aea47 and 9f946f983 and fills up some missing parts.

Add Evidences to block

---

README.md

Update the introductory section in README.md

---

Cargo.lock
Cargo.toml
voting/Cargo.toml
voting/src/general_meeting.rs
voting/src/lib.rs

This contains the structure of the GeneralMeeting module.
It does not contain any detail of the GeneralMeeting module.

Add voting module structure

---

Cargo.lock
voting/Cargo.toml
voting/src/general_meeting.rs

Read and write admin of GeneralMeeting module

---

voting/src/general_meeting.rs
voting/src/voting.rs

This PR should be merged after this [PR](https://github.com/CodeChain-io/foundry/pull/470) have merged.

Implement PublishResult Transaction

---

Cargo.lock
Cargo.toml
voting/Cargo.toml
voting/src/common.rs
voting/src/general_meeting.rs
voting/src/lib.rs
voting/src/voting.rs

In this PR, we merge the voting module to the new branch, voting, and upgrade its dependencies to the latest version.

Merge and upgrade voting module 

---

voting/src/voting.rs

`vote_manager` service should be included in export services.

Add missing export service for voting module

---

voting/src/voting.rs
voting/tests/common/mock_coordinator.rs
voting/tests/common/scenarios.rs
voting/tests/integration_test.rs

This PR will be rebased after #483 is merged.

Add tests for Vote transaction.

---

.mergify.yml

This will fix issue #87 . 
Previously, the mergify worked, but since we are using new Travis CI, we need to change `status-success` condition.

Fix mergify auto merge

---

core/src/client/client.rs

Before this commit, check_genesis_root was checking whether the DB
contains 0x0 or not.
Before this commit, Foundry fail to read the DB generated before since
the DB does not have the entity of 0x0. After this commit, Foundry
succeed to read the DB to run.

Set scheme's state root before calling check_genesis_root

---

graphql/src/lib.rs
graphql/tests/integration_test.rs

- for GET, it accepts as a string
- for POST, it accepts as a JSON object.

Handle GraphQL variables properly

---

graphql-engine/src/lib.rs
timestamp/src/util/mod.rs

That is the recommended way in async-graphql 2.0

Use Result instead of FieldResult

---

demo/app-desc.toml

It was missed while changing yml app descriptor to toml file.

Fix app descriptor in demo

---

demo/config0.ini
demo/config1.ini
demo/config2.ini
demo/config3.ini
foundry/config/presets/config.dev.ini
foundry/config/presets/config.prod.ini

* We need a "Defaults" section name.
* Comments should be in a new line.
* "" can't be used as a default value.

Fix config files

---

coordinator/src/app_desc/params.rs
foundry/main.rs
foundry/run_node.rs
foundry/tests/mod.rs
timestamp/app-desc.toml

I've failed to create an example to override app desc values.
We may need a integration test environment to test it.
I manually tested it by changing timestamp/app_desc.toml and printing it in module constructor.

Receive CLI args for modules

---

coordinator/src/desc_common/params.rs
coordinator/src/weaver/test.rs
core/src/consensus/validator_set/dynamic_validator.rs
json/src/bytes.rs
module/src/impls/process.rs
network/src/p2p/handler.rs
state/src/impls/top_level.rs

We are using "stable" toolchain of clippy in GitHub actions. Recently,
a new rust stable toolchain is release. This commit will fix Clippy
checks in the master branch.

Fix clippy errors

---

coordinator/src/weaver.rs
foundry/config/mod.rs
foundry/run_node.rs
rpc/src/v1/impls/snapshot.rs
sync/src/block/extension.rs

I tried to remove `unwrap` in Foundry initialization code.
`unwrap` makes programmers read code difficult.

Give default values to config arguments

---

integration-test/src/lib.rs
util/logger/src/macros.rs

Add MODULE log target

---

key/src/encryption.rs
key/src/encryption/keypair.rs
key/src/encryption/private.rs
key/src/encryption/public.rs
key/src/lib.rs
key/src/random.rs

It will be used in the voting module.

Add encryption/decryption code

---

Cargo.lock
Cargo.toml
graphql-engine/Cargo.toml
graphql-engine/src/lib.rs
graphql-types/Cargo.toml
graphql-types/src/lib.rs
integration-test/Cargo.toml
integration-test/src/lib.rs
integration-test/tests/integration_test.rs
timestamp/Cargo.toml
timestamp/src/account/services.rs
timestamp/src/common.rs

Add GraphQL field for transaction events

---

graphql-engine/src/lib.rs
graphql-types/src/lib.rs

It reduces the overhead of hex-en/decoding of strings in
field implementations

Add GqlBytes
